spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mctdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none #create
    properties:
      hibernate:
      # show_sql: true
      format_sql: true
#logging:
 # level:
  #  org.hibernate.SQL: debug
# org.hibernate.type: trace